# role-developer.yaml роль для разработчиков, которая может только просматривать ресурсы кластера
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: role-developer
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources: ["pods", "services", "deployments", "jobs"]
  verbs: ["get", "list", "watch"]